### ISSUE TITLE
"Authentication failed: Anmeldefehler: Alle Module werden ignoriert" when calling getProductList

### ISSUE THREAD

**Issue by novawish** [gsauthof/frank#1]
Hello,

I tried to run `examples/products.py` with my credentials, the authorization was (assumed) ok with my username and password.
However I received this message when calling function `getProductList` of `ProductInformation`:

>   File "/usr/local/lib/python3.5/dist-packages/zeep/wsdl/bindings/soap.py", line 299, in process_error
>     detail=fault_node.find("detail"),
> zeep.exceptions.Fault: Authentication failed: Anmeldefehler: Alle Module werden ignoriert
> 

Apparently I used the wrong value for `mandantid`, I tried with all information I got from `pcf-1click@deutschepost.de` but none succeed.
Could you please tell me which information should i give for `mandantid`? And where I can get it from?
Thanks very much

**Comment by gsauthof** [comment]
The Deutsche Post takes [Conway's law](https://en.wikipedia.org/wiki/Conway%27s_law) very seriously.

Thus, when they added the product query feature they added a complete new API that requires a different account/credentials.

Thus, you have to write to the Deutsche Post support email address and explicitly request a 'ProdWS' account.

To summarize: you need a 1C4A account for buying postage and a ProdWS account for querying the products.
